// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyATZKjW6i_7zHnWE0LXzUo-gooT9jt3KnA',
    appId: '1:871651311558:web:492eed1e26d64ba8bffcc7',
    messagingSenderId: '871651311558',
    projectId: 'music-app-62ae8',
    authDomain: 'music-app-62ae8.firebaseapp.com',
    storageBucket: 'music-app-62ae8.firebasestorage.app',
    measurementId: 'G-4NSQ78LMRL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAvynM7Nyom1im6vsNq6J10zQqLGoxaSRA',
    appId: '1:871651311558:android:6e89ab2dc6b94d35bffcc7',
    messagingSenderId: '871651311558',
    projectId: 'music-app-62ae8',
    storageBucket: 'music-app-62ae8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBYpon9ljR7cyd6l1aVsKQrfOYndYeIZsQ',
    appId: '1:871651311558:ios:33a2e3bb5ca4d5cfbffcc7',
    messagingSenderId: '871651311558',
    projectId: 'music-app-62ae8',
    storageBucket: 'music-app-62ae8.firebasestorage.app',
    iosBundleId: 'com.example.bankacilikUygulamasi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBYpon9ljR7cyd6l1aVsKQrfOYndYeIZsQ',
    appId: '1:871651311558:ios:33a2e3bb5ca4d5cfbffcc7',
    messagingSenderId: '871651311558',
    projectId: 'music-app-62ae8',
    storageBucket: 'music-app-62ae8.firebasestorage.app',
    iosBundleId: 'com.example.bankacilikUygulamasi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyATZKjW6i_7zHnWE0LXzUo-gooT9jt3KnA',
    appId: '1:871651311558:web:dd124470c2c205afbffcc7',
    messagingSenderId: '871651311558',
    projectId: 'music-app-62ae8',
    authDomain: 'music-app-62ae8.firebaseapp.com',
    storageBucket: 'music-app-62ae8.firebasestorage.app',
    measurementId: 'G-28N0PTJFVG',
  );
}
